import {
  PlanetType,
  ResourceType,
} from '../../../libs/prisma/generated/prisma/enums';

export const RESOURCE_PLANET_POOL: Record<PlanetType, ResourceType[]> = {
  BLACKHOLE: [],
  EXOTIC: [],
  FROZEN: [],
  LUSH: [],
  ROCKY: [],
  TOXIC: [],
};

export const BASE_AMOUNT_RESOURCE: Record<ResourceType, [number, number]> = {
  ADRA: [0, 0],
  ALPHACREDITS: [0, 0],
  ALUMINUM: [0, 0],
  AMMONIA: [0, 0],
  BETATOKENS: [0, 0],
  BORON: [0, 0],
  CALCIUM: [0, 0],
  CARBON: [0, 0],
  CHROMIUM: [0, 0],
  COAL: [0, 0],
  COBALT: [0, 0],
  COPPER: [0, 0],
  DEUTERIUM: [0, 0],
  DILITHIUM: [0, 0],
  EXOTICMATTER: [0, 0],
  GAMMARSHARDS: [0, 0],
  GOLD: [0, 0],
  HELIUM3: [0, 0],
  IRIDIUM: [0, 0],
  KYRIPTONITE: [0, 0],
  LITHIUM: [0, 0],
  MAGNESIUM: [0, 0],
  MANGANESE: [0, 0],
  METHANE: [0, 0],
  MOLYBDENUM: [0, 0],
  NAQUADA: [0, 0],
  NEUTRONIUM: [0, 0],
  NICKEL: [0, 0],
  OBSIDIAN: [0, 0],
  OSMIUM: [0, 0],
  PALLADIUM: [0, 0],
  PHOSPHORUS: [0, 0],
  PLATINUM: [0, 0],
  QUANTUMORE: [0, 0],
  RHODIUM: [0, 0],
  RUTHENIUM: [0, 0],
  SILICON: [0, 0],
  STRYDIUM: [0, 0],
  SULFUR: [0, 0],
  TITANIUM: [0, 0],
  TRILLIUM: [0, 0],
  TRITIUM: [0, 0],
  TUNGSTEN: [0, 0],
  UNOBTANIUM: [0, 0],
  URANIUM: [0, 0],
  VERYNIUM: [0, 0],
  WATERICE: [0, 0],
  ZINC: [0, 0],
};

export const PREFIXES_NAME_PLANET: string[] = [
  'Zor',
  'Krag',
  'Neb',
  'Vort',
  'Ely',
  'Thar',
  'Drak',
  'Syl',
  'Quor',
  'Xan',
];

export const SUFFIXES_NAME_PLANET: string[] = [
  'Prime',
  'Alpha',
  'Beta',
  'Void',
  'Nexus',
  'Core',
  'Rift',
  'Storm',
  'Dust',
  'Ice',
];
